import { z } from "zod";

const HABIT_TRACKER_API_SCHEMA = z.string();
const HABIT_TRACKER_API_HOST = z.string();
const HABIT_TRACKER_API_PORT = z.coerce.number().positive();
const HABIT_TRACKER_API_BASE_PATH = z.string();

export const habitTrackerAPIEnvSchema = {
	HABIT_TRACKER_API_SCHEMA,
	HABIT_TRACKER_API_HOST,
	HABIT_TRACKER_API_PORT,
	HABIT_TRACKER_API_BASE_PATH,
};

export const viteHabitTrackerAPIEnvSchema = {
	VITE_HABIT_TRACKER_API_SCHEMA: HABIT_TRACKER_API_SCHEMA,
	VITE_HABIT_TRACKER_API_HOST: HABIT_TRACKER_API_HOST,
	VITE_HABIT_TRACKER_API_PORT: HABIT_TRACKER_API_PORT,
	VITE_HABIT_TRACKER_API_BASE_PATH: HABIT_TRACKER_API_BASE_PATH,
};
